name: City Visions
favicon: null
layout_spectrum: 0.5744681
typography_spectrum: 0.38825
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#548aba'
    - '#050505'
    - '#83bcdd'
    - '#f0c277'
  brandStrength: 0.1875
  lightness: 0.6875
  saturation: 0.25
  rhythmicContrast: 0.3361702
purpose: []
