favicon: null
name: City Visions
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.25
  brandStrength: 0.625
  rhythmicContrast: 0.75
  brandColors:
    - '#ffffff'
    - '#060606'
    - '#8999a6'
    - '#e52628'
    - '#d8c99d'
  lightness: 0.6875
typography_spectrum: 0.38825
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.5744681
analytics:
  twitter: null
  google: null
  facebook: null
