name: cityvisions
favicon: null
layout_spectrum: 0.759034572634846
typography_spectrum: 0.6321889574173838
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7897b5'
    - '#a7e0ff'
    - '#a68e74'
    - '#817670'
    - '#f9c99b'
  brandStrength: 0.5384497379418463
  lightness: 0.1910541784018278
  saturation: 0.6000407673418522
  rhythmicContrast: 0.7128304170910269
purpose: []
